const gameData =
    [{
        category: "Deck",
        words: [
            { word: "supplychainvisibility", hint: "Hint" },
            { word: "wtms", hint: "Hint" },
            { word: "replenishmentmanager", hint: "Hint" },
            { word: "storemanager", hint: "Hint" },
            { word: "supplychain", hint: "Hint" },
            { word: "replenishment", hint: "Hint" },
            { word: "gigaton", hint: "Hint" },
            { word: "greenhouse", hint: "Hint" },
            { word: "sustainability", hint: "Hint" },
            { word: "ecofriendly", hint: "Hint" },
            { word: "emailcategorization", hint: "Hint" },
            { word: "surveyresultautomation", hint: "Hint" },
            { word: "silverlight", hint: "Hint" },
            { word: "websphere", hint: "Hint" },
            { word: "oneops", hint: "Hint" },
            { word: "spotlightreporting", hint: "Hint" },
            { word: "graylog", hint: "Hint" },
            { word: "nightwatchjs", hint: "Hint" },
            { word: "eol", hint: "Hint" },
            { word: "topend", hint: "Hint" },
            { word: "retaillink", hint: "Hint" },
            { word: "opensourcebi", hint: "Hint" },
            { word: "otif", hint: "Hint" },
            { word: "springboot", hint: "Hint" },
            { word: "supplierperformance", hint: "Hint" },
            { word: "wmsdatacentralization", hint: "Hint" },
            { word: "backorderrate", hint: "Hint" },
            { word: "enterpriselevelorderleadtime", hint: "Hint" },
            { word: "datalakestore", hint: "Hint" },
            { word: "datalakeanalytics", hint: "Hint" },
            { word: "hdinsight", hint: "Hint" },
            { word: "streamingdb", hint: "Hint" },
            { word: "specializeddw", hint: "Hint" },
            { word: "azurecosmosdb", hint: "Hint" },
            { word: "distributioncenters", hint: "Hint" },
            { word: "nifi", hint: "Hint" },
            { word: "azuredatalake", hint: "Hint" },
            { word: "asda", hint: "Hint" },
            { word: "asdalockerbox", hint: "Hint" },
            { word: "reactnative", hint: "Hint" },
            { word: "tableau", hint: "Hint" },
            { word: "customerretention", hint: "Hint" },
            { word: "clickandcollect", hint: "Hint" },
            { word: "collectionpoint", hint: "Hint" },
            { word: "walmartinternational", hint: "Hint" },
            { word: "wms", hint: "Hint" },
            { word: "warehouse", hint: "Hint" },
            { word: "palletized", hint: "Hint" },
            { word: "manifest", hint: "Hint" },
            { word: "geofence", hint: "Hint" },
            { word: "sku", hint: "Hint" },
            { word: "dcnetwork", hint: "Hint" },
            { word: "shockalert", hint: "Hint" },
            { word: "fleetefficiency", hint: "Hint" },
            { word: "fertilizeroptimization", hint: "Hint" },
            { word: "deforestation", hint: "Hint" },
            { word: "mcfnaturalgas", hint: "Hint" },
            { word: "psn", hint: "Hint" },
            { word: "alteryx", hint: "Hint" },
            { word: "scheduleadherence", hint: "Hint" },
            { word: "locmodernized", hint: "Hint" },
            { word: "moengagement", hint: "Hint" },
            { word: "aix", hint: "Hint" }
        ]
    }];

module.exports = gameData;
